# Generated by Django 3.1.3 on 2020-11-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201118_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='', max_length=50)),
                ('pname', models.CharField(max_length=100)),
                ('price_per_unit', models.FloatField()),
                ('qty', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('doe', models.DateTimeField()),
                ('mfd', models.DateField()),
                ('exp', models.DateField()),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
