# Generated by Django 3.1.3 on 2020-11-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201122_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('purchase_items', models.JSONField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'billing',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_per_unit',
            new_name='price',
        ),
    ]
