# Generated by Django 3.1.3 on 2020-11-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201122_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='others', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='doe',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
