# Generated by Django 3.1.3 on 2020-12-03 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201122_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='qr_codes'),
            preserve_default=False,
        ),
    ]
