# Generated by Django 3.1.3 on 2021-01-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.CharField(default='bikash', max_length=20),
            preserve_default=False,
        ),
    ]
